name: ecommerce_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  get: ^4.6.5
  material_design_icons_flutter: ^6.0.7096
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  flutter_login_facebook: ^1.8.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.5.1
  iconly: ^1.0.1
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
  fonts:

      - family: IconBroken
        fonts:
          - asset: assets/fonts/icons.ttf
      - family: SourceSansPro
        fonts:
          - asset: assets/fonts/SourceSansPro.ttf

